M48
; DRILL file {KiCad (6.0.8)} date Tue Nov 15 21:15:24 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-15T21:15:24+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X179.07Y-62.865
X179.07Y-156.21
X272.4Y-62.7
X272.796Y-156.464
T0
M30
